# Generated by Django 2.2.1 on 2019-05-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('username', models.CharField(default=None, max_length=200, null=True)),
                ('password', models.CharField(default=None, max_length=200, null=True)),
                ('email', models.CharField(default=None, max_length=200, null=True)),
                ('phone', models.CharField(default=None, max_length=200, null=True)),
                ('image', models.CharField(default='https://cdn1.vectorstock.com/i/1000x1000/82/55/anonymous-user-circle-icon-vector-18958255.jpg', max_length=400, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=2000),
        ),
    ]
