# Generated by Django 2.2.1 on 2019-05-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190522_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(to='api.Book'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='client',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Client'),
        ),
    ]
