# Generated by Django 2.2.1 on 2019-05-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190523_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(default=None, null=True, to='api.Book'),
        ),
    ]
