# Generated by Django 2.2.1 on 2019-05-22 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190523_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('comment', models.TextField()),
                ('book', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Book')),
                ('client', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
        ),
    ]
